name: home-server-minecraft-tailnet

services:
  minecraft-tailscale:
    image: tailscale/tailscale@sha256:8c42c4574ab066384fcb72f69e086a2ff1dd3652eb6f56856cee34bcf0d2f680
    container_name: minecraft-tailscale

    network_mode: "service:minecraft"

    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: "false"
      TS_EXTRA_ARGS: "--accept-dns=false"

    volumes:
      - ${APPDATA}/tailscale-minecraft:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun

    cap_add:
      - NET_ADMIN
      - NET_RAW

    command: tailscaled

    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M