#!/usr/bin/env bash

set -euo pipefail

# ---------------------------------------------------------------------------
# configure-acme-hook.sh
#
# Generates a standalone copy of npm-cert-update.sh in the user's home
# directory and registers it as the acme.sh reload hook.
#
# The project version of npm-cert-update.sh is NOT modified.
#
# Generated hook:
#
#     ~/DOMAIN_NAME-npm-cert-update.sh
#
# Example:
#
#     ~/eggbase.net-npm-cert-update.sh
#
# DOMAIN_NAME and IP_ADDRESS are injected into the generated hook so that
# acme.sh does not need access to the project .env file.
#
# ---------------------------------------------------------------------------

LOG_TAG="[acme-hook]"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

ENV_FILE="${PROJECT_ROOT}/.env"
SOURCE_SCRIPT="${SCRIPT_DIR}/npm-cert-update.sh"

# ---------------------------------------------------------------------------
# Read value from .env
# ---------------------------------------------------------------------------

read_env_value() {
    local key="$1"
    local value=""

    if [[ -f "${ENV_FILE}" ]]; then
        value="$(
            grep -E "^${key}=" "${ENV_FILE}" |
            tail -n1 |
            cut -d '=' -f2- ||
            true
        )"

        value="${value%\"}"
        value="${value#\"}"

        value="${value%\'}"
        value="${value#\'}"
    fi

    echo "${value}"
}

# ---------------------------------------------------------------------------
# Resolve DOMAIN_NAME
# ---------------------------------------------------------------------------

DOMAIN_NAME="${DOMAIN_NAME:-}"

if [[ -z "${DOMAIN_NAME}" ]]; then
    DOMAIN_NAME="$(read_env_value DOMAIN_NAME)"
fi

if [[ -z "${DOMAIN_NAME}" ]]; then
    echo "${LOG_TAG} ERROR: DOMAIN_NAME is not set."
    echo
    echo "${LOG_TAG} Add it to:"
    echo
    echo "    ${ENV_FILE}"
    echo
    echo "Example:"
    echo
    echo "    DOMAIN_NAME=eggbase.net"
    exit 1
fi

# ---------------------------------------------------------------------------
# Resolve IP_ADDRESS
# ---------------------------------------------------------------------------

IP_ADDRESS="${IP_ADDRESS:-}"

if [[ -z "${IP_ADDRESS}" ]]; then
    IP_ADDRESS="$(read_env_value IP_ADDRESS)"
fi

if [[ -z "${IP_ADDRESS}" ]]; then
    echo "${LOG_TAG} ERROR: IP_ADDRESS is not set."
    echo
    echo "${LOG_TAG} Add it to:"
    echo
    echo "    ${ENV_FILE}"
    echo
    echo "Example:"
    echo
    echo "    IP_ADDRESS=192.168.100.65"
    exit 1
fi

# ---------------------------------------------------------------------------
# Validate source
# ---------------------------------------------------------------------------

if [[ ! -f "${SOURCE_SCRIPT}" ]]; then
    echo "${LOG_TAG} ERROR: Source script not found:"
    echo
    echo "    ${SOURCE_SCRIPT}"
    exit 1
fi

# ---------------------------------------------------------------------------
# Generated hook path
# ---------------------------------------------------------------------------

HOOK_PATH="${HOME}/${DOMAIN_NAME}-npm-cert-update.sh"

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------

echo
echo "${LOG_TAG} ==============================================="
echo "${LOG_TAG} CONFIGURE ACME HOOK"
echo "${LOG_TAG} ==============================================="
echo
echo "${LOG_TAG} Domain:"
echo "    ${DOMAIN_NAME}"
echo
echo "${LOG_TAG} IP Address:"
echo "    ${IP_ADDRESS}"
echo
echo "${LOG_TAG} Source:"
echo "    ${SOURCE_SCRIPT}"
echo
echo "${LOG_TAG} Installing standalone hook:"
echo "    ${HOOK_PATH}"
echo

# ---------------------------------------------------------------------------
# Generate hook
# ---------------------------------------------------------------------------

TMP_FILE="$(mktemp)"

cleanup() {
    rm -f "${TMP_FILE}"
}

trap cleanup EXIT

{
    echo '#!/usr/bin/env bash'
    echo
    echo '# ---------------------------------------------------------------------------'
    echo '# AUTO-GENERATED ACME HOOK'
    echo '#'
    echo '# Generated by configure-acme-hook.sh'
    echo '#'
    echo '# DO NOT EDIT THIS FILE MANUALLY.'
    echo '# Regenerate it with:'
    echo '#'
    echo '#     bash configure-acme-hook.sh'
    echo '#'
    echo '# ---------------------------------------------------------------------------'
    echo

    printf 'DOMAIN_NAME=%q\n' "${DOMAIN_NAME}"
    printf 'IP_ADDRESS=%q\n' "${IP_ADDRESS}"
    echo
    echo 'export DOMAIN_NAME'
    echo 'export IP_ADDRESS'
    echo

    # Skip the original shebang.
    tail -n +2 "${SOURCE_SCRIPT}"

} > "${TMP_FILE}"

# ---------------------------------------------------------------------------
# Install with correct permissions
# ---------------------------------------------------------------------------

install \
    -m 700 \
    "${TMP_FILE}" \
    "${HOOK_PATH}"

rm -f "${TMP_FILE}"
trap - EXIT

echo "${LOG_TAG} Standalone hook installed."
echo

ls -l "${HOOK_PATH}"

# ---------------------------------------------------------------------------
# Verify executable
# ---------------------------------------------------------------------------

if [[ ! -x "${HOOK_PATH}" ]]; then
    echo
    echo "${LOG_TAG} ERROR: Generated hook is not executable."
    exit 1
fi

# ---------------------------------------------------------------------------
# Register with acme.sh
# ---------------------------------------------------------------------------

echo
echo "${LOG_TAG} Registering hook with acme.sh..."
echo

"${HOME}/.acme.sh/acme.sh" \
    --install-cert \
    -d "${DOMAIN_NAME}" \
    --reloadcmd "${HOOK_PATH}"

# ---------------------------------------------------------------------------
# Verify acme.sh configuration
# ---------------------------------------------------------------------------

echo
echo "${LOG_TAG} ==============================================="
echo "${LOG_TAG} HOOK CONFIGURATION COMPLETE"
echo "${LOG_TAG} ==============================================="
echo
echo "${LOG_TAG} Domain:"
echo "    ${DOMAIN_NAME}"
echo
echo "${LOG_TAG} IP Address:"
echo "    ${IP_ADDRESS}"
echo
echo "${LOG_TAG} Hook:"
echo "    ${HOOK_PATH}"
echo
echo "${LOG_TAG} Permissions:"
ls -l "${HOOK_PATH}"
echo
echo "${LOG_TAG} Embedded configuration:"
grep -E '^(DOMAIN_NAME|IP_ADDRESS)=' "${HOOK_PATH}"
echo
echo "${LOG_TAG} acme.sh reload command:"
grep -F "Le_ReloadCmd" \
    "${HOME}/.acme.sh/${DOMAIN_NAME}_ecc/${DOMAIN_NAME}.conf" \
    || true
echo
echo "${LOG_TAG} Done."