name: Deploy Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, eggbase-net]

    steps:
      - name: Deploy
        run: ~/home-server/scripts/deploy.sh